import * as vscode from 'vscode';
import { HarEntry } from 'har-parser';

/**
 * Represents a recorded HAR call with metadata
 */
export interface RecordedCall {
  id: string;
  timestamp: string;
  entry: HarEntry;
}

/**
 * Format for the JSONC file containing recorded calls
 */
export interface RecordingFile {
  extensionId: string;
  calls: RecordedCall[];
}

/**
 * Manages persistence of HAR calls to JSONC files in workspace storage
 */
export class RecordingManager {
  private readonly storageUri: vscode.Uri;
  private writePromises: Map<string, Promise<void>> = new Map();

  constructor(private readonly context: vscode.ExtensionContext) {
    this.storageUri = context.globalStorageUri;
  }

  /**
   * Initialize the recording manager and ensure storage directory exists
   */
  async initialize(): Promise<void> {
    try {
      await vscode.workspace.fs.createDirectory(this.storageUri);
    } catch (error) {
      // Directory might already exist, which is fine
      console.log('Storage directory already exists or error creating:', error);
    }
  }

  /**
   * Get the file path for a specific extension's recording file
   */
  private getRecordingFilePath(extensionId: string): vscode.Uri {
    const fileName = `recording-${extensionId}.jsonc`;
    return vscode.Uri.joinPath(this.storageUri, fileName);
  }

  /**
   * Generate a unique ID for a call
   */
  private generateCallId(): string {
    return `call-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
  }

  /**
   * Read existing recording file or create new one
   */
  private async readRecordingFile(extensionId: string): Promise<RecordingFile> {
    const filePath = this.getRecordingFilePath(extensionId);

    try {
      const fileContent = await vscode.workspace.fs.readFile(filePath);
      const decoder = new TextDecoder('utf-8');
      const content = decoder.decode(fileContent);

      // Strip JSONC comments for parsing
      const jsonContent = content.replace(/\/\*[\s\S]*?\*\/|\/\/.*/g, '');
      const parsed = JSON.parse(jsonContent);

      return {
        extensionId,
        calls: parsed.calls || []
      };
    } catch (error) {
      // File doesn't exist or is invalid, return empty structure
      return {
        extensionId,
        calls: []
      };
    }
  }

  /**
   * Write recording file with atomic write operation
   */
  private async writeRecordingFile(extensionId: string, data: RecordingFile): Promise<void> {
    const filePath = this.getRecordingFilePath(extensionId);

    // Add JSONC header comment
    const header = `// HAR Recording for extension: ${extensionId}\n// Generated by HAR Visualizer\n// Last updated: ${new Date().toISOString()}\n\n`;

    const content = header + JSON.stringify(data, null, 2);
    const encoder = new TextEncoder();
    const buffer = encoder.encode(content);

    // Use atomic write by writing to temp file first, then renaming
    const tempFilePath = vscode.Uri.joinPath(
      this.storageUri,
      `recording-${extensionId}.tmp`
    );

    try {
      await vscode.workspace.fs.writeFile(tempFilePath, buffer);
      await vscode.workspace.fs.rename(tempFilePath, filePath, { overwrite: true });
    } catch (error) {
      // Clean up temp file on error
      try {
        await vscode.workspace.fs.delete(tempFilePath);
      } catch { }
      throw error;
    }
  }

  /**
   * Append a HAR call to the recording file for a specific extension
   * Ensures sequential writes using promise chaining
   */
  async appendCall(extensionId: string, entry: HarEntry): Promise<string> {
    // Chain this write after any pending write for this extension
    const previousWrite = this.writePromises.get(extensionId) || Promise.resolve();

    const writeOperation = previousWrite
      .then(async () => {
        const callId = this.generateCallId();
        const recordedCall: RecordedCall = {
          id: callId,
          timestamp: new Date().toISOString(),
          entry
        };

        const recordingFile = await this.readRecordingFile(extensionId);
        recordingFile.calls.push(recordedCall);

        await this.writeRecordingFile(extensionId, recordingFile);

        return callId;
      })
      .catch((error) => {
        console.error(`Error appending call to recording for ${extensionId}:`, error);
        throw new Error(`Failed to append call: ${error.message}`);
      });

    // Store the promise for chaining
    this.writePromises.set(extensionId, writeOperation.then(() => {}));

    return writeOperation;
  }

  /**
   * Get all recorded calls for a specific extension
   */
  async getCalls(extensionId: string): Promise<RecordedCall[]> {
    const recordingFile = await this.readRecordingFile(extensionId);
    return recordingFile.calls;
  }

  /**
   * Clear all recorded calls for a specific extension
   */
  async clearCalls(extensionId: string): Promise<void> {
    const filePath = this.getRecordingFilePath(extensionId);

    try {
      await vscode.workspace.fs.delete(filePath);
    } catch (error) {
      // File might not exist, which is fine
      console.log(`No recording file to clear for ${extensionId}`);
    }
  }

  /**
   * Get the file path for a specific extension (for external access)
   */
  getRecordingFileUri(extensionId: string): vscode.Uri {
    return this.getRecordingFilePath(extensionId);
  }

  /**
   * List all extension IDs that have recordings
   */
  async listRecordedExtensions(): Promise<string[]> {
    try {
      const files = await vscode.workspace.fs.readDirectory(this.storageUri);
      const extensionIds: string[] = [];

      for (const [fileName, fileType] of files) {
        if (fileType === vscode.FileType.File && fileName.startsWith('recording-') && fileName.endsWith('.jsonc')) {
          const extensionId = fileName.replace('recording-', '').replace('.jsonc', '');
          extensionIds.push(extensionId);
        }
      }

      return extensionIds;
    } catch (error) {
      console.error('Error listing recorded extensions:', error);
      return [];
    }
  }
}
